### ISSUE TITLE
Access Bitbucket Repos

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [grosser/repo_dependency_graph#3]
@grosser I am trying to get a dependency graph of all repos under project QA(http://<host>/bitbucket/rest/api/1.0/projects/QA) from Bitbucket at my workplace. Can I access Bibucket repos at my workplace? I am trying the options you provided but they are not working.
```
$ repo-dependency-graph --user <bitbucket_user>
<path>/gems/3.2.0/gems/organization_audit-2.1.1/lib/organization_audit/repo.rb:45:in `all': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from <path>/gems/3.2.0/gems/repo_dependency_graph-0.6.0/lib/repo_dependency_graph.rb:14:in `dependencies'
        from <path>/gems/3.2.0/gems/repo_dependency_graph-0.6.0/lib/repo_dependency_graph/cli.rb:10:in `run'
        from <path>/gems/3.2.0/gems/repo_dependency_graph-0.6.0/bin/repo-dependency-graph:7:in `<top (required)>'
        from <path>/bin/repo-dependency-graph:25:in `load'
        from <path>/bin/repo-dependency-graph:25:in `<main>'

```

**Comment by grosser** [comment]
the error seems like there is something broken internally, so needs some digging if you want to take a look
`bundle open repo_dependency_graph` should get you started
also this gem is not made for bitbucket, so if it does not have the same api then it won't work without some more maodifications

**Comment by pgundlupetvenkatesh** [comment]
Ah okay... Thanks for letting me know on the Bitbucket.
